development:
  perform_authentication: true
  STORMSAVVY_GMAIL_USERNAME: alerts@stormsavvy.com
  STORMSAVVY_GMAIL_PASSWORD: DarkAndStormy

test:
  perform_authentication: true
  STORMSAVVY_GMAIL_USERNAME: alerts@stormsavvy.com
  STORMSAVVY_GMAIL_PASSWORD: DarkAndStormy

production:
  perform_authentication: false
  STRIPE_API_KEY: sk_live_7GfB1PylLNMf8v26RITa95Iu
  STRIPE_PUBLIC_KEY: pk_live_GBRP0mjjNUNrr8n2coIa0Z0f